### ISSUE TITLE
Write .nrepl-port file for better tooling interop

### ISSUE THREAD

**Issue by cichli** [jarohen/embed-nrepl#1]
Leiningen writes an `.nrepl-port` file in the project root when you run `lein repl`, containing the port of the running nREPL server - tools like CIDER then check for this file to auto-suggest port numbers to connect to. Relevant code is [here](https://github.com/technomancy/leiningen/blob/3ba4fde63361c0986df6d08366132f5d6b7bdb12/src/leiningen/repl.clj#L317-L324) and [here](https://github.com/technomancy/leiningen/blob/3ba4fde63361c0986df6d08366132f5d6b7bdb12/src/leiningen/repl.clj#L18-L28).

**Comment by jarohen** [comment]
Yes, if you want to submit a PR ;)

Cheers Mike!
